declare global {
  interface ImportMeta {
    readonly dir: string;
  }
}

declare const Bun: {
  readonly Glob: new (pattern: string) => {
    scan(options: { readonly cwd: string }): AsyncIterable<string>;
  };
  write(path: string, data: string): Promise<number>;
};

const routeDirectory = `${import.meta.dir}/../src/routes`;
const outputFile = `${import.meta.dir}/../src/routes.generated.ts`;
const routeFiles: string[] = [];

for await (const file of new Bun.Glob('*.tsx').scan({ cwd: routeDirectory })) {
  routeFiles.push(file);
}

routeFiles.sort((left, right) => left.localeCompare(right));

if (routeFiles.length === 0) {
  throw new Error('No route modules found in src/routes.');
}

const importLines = routeFiles.map(
  (file, index) => `import route${index} from './routes/${file.replace(/\.tsx$/, '')}';`,
);
const childRoutes = routeFiles.map((_, index) => `route${index}`).join(', ');

const generated = [
  '// This file is generated by scripts/generate-routes.ts. Do not edit by hand.',
  '',
  "import { createRoute } from 'rxjs-router';",
  "import { loadRootData } from './routes/root';",
  ...importLines,
  '',
  `export const generatedRouteFiles = ${JSON.stringify(routeFiles)} as const;`,
  '',
  'export const routes = [',
  '  createRoute({',
  "    id: 'root',",
  "    path: '/',",
  '    loader: loadRootData,',
  `    children: [${childRoutes}],`,
  '  }),',
  '] as const;',
  '',
].join('\n');

await Bun.write(outputFile, generated);
console.log(`Generated ${routeFiles.length} route modules.`);

export {};
