// This file is generated by scripts/generate-routes.ts. Do not edit by hand.

import { createRoute } from 'rxjs-router';
import { loadRootData } from './routes/root';
import route0 from './routes/about';
import route1 from './routes/counter';
import route2 from './routes/home';
import route3 from './routes/todos';

export const generatedRouteFiles = ["about.tsx","counter.tsx","home.tsx","todos.tsx"] as const;

export const routes = [
  createRoute({
    id: 'root',
    path: '/',
    loader: loadRootData,
    children: [route0, route1, route2, route3],
  }),
] as const;
